name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.x', '3.x', 'pypy2', 'pypy3' ]
    name: Python version ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install click
    - name: Run program
      run: |
        python generator_datasets.py -j data/dataset.json
        
