name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Code analysis with PyLint
      run: |
        python -m pylint --reports=y text generator_datasets.py
    - name: Run program
      run: |
        python generator_datasets.py -j data/dataset.json
        
        
        
        
