name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install libraries
      run: |
        python -m pip install --upgrade pip
        pip install click
    - name: Run program
      run: |
        python generator_datasets.py -j data/dataset.json
